- package-lock.json
- package.json
- src/components/pages/Chat/AddRoomItem.tsx
- src/lib/ChatRoomManager.ts
Uuids are ugly and hard to keep track of, replace with a 3 word sentence as proposed
For a first run use this NPM package for the random name generation:
https://www.npmjs.com/package/unique-names-generator
> FRONT-824: Replace default room names with randomly generated ones

- package-lock.json
- package.json
- src/components/SessionHandler.ts
- src/components/Store.tsx
- src/components/pages/Chat/RoomItem.tsx
- src/components/pages/Chat/index.tsx
- src/getters/getInitialStoreState.ts
- src/hooks/useExistingRooms.ts
- src/hooks/useInviter.ts
- src/hooks/useRoomIdsStorage.ts
- src/lib/ChatRoomManager.ts
- src/utils/types.ts
Too late for a description. I'm out.
@bearni95 please have a look, tell me what you think. Mostly yours, rearranged.
NOTE: I don't generate fully fledged room structures like it used to be. Storing only the id. I'll make each room tile (or something similar) take care of that and all the comms stuff. That's the plan.
> Refactor the initial room fetching, room id storage, etc.

- src/components/Store.tsx
- src/components/pages/Chat/AddRoomItem.tsx
- src/components/pages/Chat/MessageTransmitter.tsx
- src/components/pages/Chat/RoomHeader.tsx
- src/components/pages/Chat/RoomItem.tsx
- src/components/pages/Chat/RoomNameDisplay.tsx
- src/components/pages/Chat/RoomNameLoader.tsx
- src/components/pages/Chat/RoomRenameProvider.tsx
- src/components/pages/Chat/index.tsx
- src/getters/getInitialStoreState.ts
- src/hooks/useRoomName.ts
- src/utils/types.ts
Renaming rooms is back. And there's a new command – `/rename <new room name>`. 💪🏻
> Room renaming with backend support

- package-lock.json
- package.json
- src/components/Store.tsx
- src/components/pages/Chat/EmptyFeed/index.tsx
- src/components/pages/Chat/MessageInterceptor.tsx
- src/components/pages/Chat/MessageTransmitter.tsx
- src/getters/getInitialStoreState.ts
- src/hooks/useCreateRoom.ts
- src/hooks/useExistingRooms.ts
- src/hooks/useInviter.ts
- src/utils/types.ts
Get the chat working with the Polygon mainnet contracts and their new methods
> FRONT-826: Upgrade streamr-client version to 6.0.0-alpha25 (OCR enabled)

- src/hooks/useCreateRoom.ts
- src/hooks/useExistingRooms.ts
- Added check for `description` to match the generated `roomName` from the `streamId`
- Removed redundant check for `ROOM_PREFIX`
- Patch for local invites and permissions check
> Add room names as part of descriptions

- src/hooks/useExistingRooms.ts
Changing order of execution on the permission checks fixed it
> Fix: Disappearing local rooms

- package-lock.json
- package.json
> Bump streamr-client from 6.0.0-alpha.30 to 6.0.0-beta.1

- src/components/Navbar.tsx
- src/components/pages/Chat/AddMemberModal/index.tsx
Trivial unused import removal. Also an unused button.
> Fix warnings for Github Actions

- src/components/RoomDropdown/index.tsx
- src/components/WalletModal/index.tsx
- src/components/pages/Chat/AddMemberModal/index.tsx
- src/components/pages/Chat/AddRoomItem.tsx
- fixed runtime warning about `strokeWidth` and `strokeLinecap`
- added consistent references to the app context on every `ReactModal` element
> Warning fixes

- src/components/pages/Chat/MessageInterceptor.tsx
- src/components/pages/Chat/PresenceEmitter.tsx
- src/components/pages/Chat/index.tsx
To keep notifying others that one is online and to also implement the "offline" status after one of these is not received for a period of time
> [FRONT-891] Periodically send MetadataType.UserOnline messages

- src/components/pages/Chat/MessageTransmitter.tsx
The `/purge` command needs an upgrade and cannot really wait until [the ERC20JoinPolicy PR](https://github.com/streamr-dev/chat/pull/127) is ready so here it is, a mini PR to upgrade _just_ the `/purge` command!
> Upgraded /purge command from ERC20JoinPolicy code

- src/components/pages/Chat/AddRoomModal/AddRoomItem.tsx
- src/components/pages/Chat/MessageInterceptor.tsx
- src/hooks/useCreateRoom.ts
Implement the functionality to enable or disable storage upon stream creation for the visual toggle button added in [this PR](https://github.com/streamr-dev/chat/pull/113)
> [FRONT-947] Stream Storage logic

- src/components/pages/Chat/MessageAggregator.tsx
- src/components/pages/Chat/RoomRenameProvider.tsx
- src/utils/types.ts
Required for [this Dependabot PR](https://github.com/streamr-dev/chat/pull/141) to properly function
> React types corrections

- src/components/pages/Chat/MessageInterceptor.tsx
Capture subscription errors and `console.warn` them.
> Add onError handler for subscriptions

- .github/workflows/deployment.yml
- src/components/pages/Chat/ChatWindow.tsx
Using the state variable `roomId` to hide or display the message input
> [FRONT-966] Remove this msg input field when there's no chatrooms or no chatroom selected

- .github/workflows/deployment.yml
- src/hooks/useExistingRooms.ts
Added auto-dispatcher for `SelectRoom` on the first room available on useExistingRooms hook, as long as a room is not selected and there is at least one to select
> [FRONT-961] Chat room should, by default, open the first chatroom in the list of chat rooms

- .github/workflows/deployment.yml
- src/components/pages/Chat/EmptyFeed/index.tsx
- Restored the "Add Member" button on the empty feed
- Implemented functionality to trigger the Add Member modal
> [FRONT-958] Newly created chat rooms should have the "Add member" button

- .github/workflows/deployment.yml
- src/components/Navbar.tsx
Since the app is single-page the link on the logo has been removed
> [FRONT-965] Clicking "thechat.eth" always asks to set the permissions even after they have been set.

- .github/workflows/deployment.yml
- src/components/EthereumProviderDetector.tsx
Added a toast to notify, without auto-close, when no Metamask provider is detected.
> [FRONT-735] Gracefully handle no Metamask on browser

- package-lock.json
- package.json
- src/components/Avatar.tsx
- src/components/Conversation/DateTooltip.tsx
- src/components/Conversation/Message.tsx
- src/components/Conversation/MessageFeed.tsx
- src/components/Conversation/MessageInput.tsx
- src/components/Tooltip.tsx
- src/components/modals/EditMembersModal.tsx
- src/features/flag/types.ts
- src/features/identicons/hooks.ts
- src/features/identicons/sagas/retrieve.saga.ts
- src/features/identicons/selectors.ts
- src/features/members/index.ts
- src/features/members/sagas/detect.saga.ts
- src/features/members/sagas/lookupDelegation.saga.ts
- src/features/members/selectors.ts
- src/features/members/types.ts
- src/features/message/index.ts
- src/features/message/sagas/publish.saga.ts
- src/features/message/sagas/resend.saga.ts
- src/hooks/useIntercept.ts
- src/hooks/useMainAccount.ts
- src/utils/authorizeDelegatedAccount.ts
- src/utils/db.ts
- src/utils/getAccountType.ts
- src/utils/getDelegatedAccessRegistry.ts
- src/utils/isAuthorizedDelegatedAccount.ts
- src/utils/toLocalMessage.ts
Few things happen in this PR:
- Message payloads are only about the content of the message
This gives us the ability, if allowed by the client, to display encrypted messages. Long story.
- We utilize the main-to-delegated address registry to read who's the real sender behind a message.
- Display sender ENS names/nicknames/addresses in the UI so that we can see who's the sender.
- Few other minor things I.. forgot to remember.
> FRONT-1055: Minimalistic payloads
